# Welcome to Jekyll!
#

# Site settings
title: Mykola Sosnovshchenko
description: |
  Personal art blog
owner: Mykola Sosnovshchenko
first_published: 2017
email: designerr86@gmail.com
baseurl: ""
url: "https://github.io" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/profile.php?id=100013651371250
  # google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:designerr86@gmail.com
  #flickr:
  instagram: https://instagram.com/violet_gentleman
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  vk: https://vk.com/tschefidiy
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
collections: 
  galleries:
  infographics:
